# Generated by Django 3.0.8 on 2020-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shenfen',
            field=models.CharField(max_length=128),
        ),
    ]
